stages:
  fetch_data:
    cmd: python src/fetch_data.py ${data.start_date} ${data.end_date} sentinel2_raw.csv
    deps:
      - src/fetch_data.py
      - src/config.py
    params:
      - data.start_date
      - data.end_date
    outs:
      - data/raw/sentinel2_raw.csv

  validate_data:
    cmd: python src/validate_data.py sentinel2_raw.csv sentinel2_validated.csv
    deps:
      - src/validate_data.py
      - data/raw/sentinel2_raw.csv
    outs:
      - data/raw/sentinel2_validated.csv

  preprocess:
    cmd: python src/preprocess.py sentinel2_validated.csv processed_features.csv scaler.pkl
    deps:
      - src/preprocess.py
      - data/raw/sentinel2_validated.csv
    outs:
      - data/processed/processed_features.csv
      - models/trained_models/scaler.pkl

  generate_labels:
    cmd: python src/generate_labels.py processed_features.csv labels.csv
    deps:
      - src/generate_labels.py
      - data/processed/processed_features.csv
    outs:
      - data/processed/labels.csv

  pretrain:
    cmd: python src/pretrain.py data/processed/processed_features.csv data/processed/labels.csv data/processed/features_for_training.csv data/processed/labels_for_training.csv data/processed/feature_scaler.pkl
    deps:
      - src/pretrain.py
      - data/processed/processed_features.csv
      - data/processed/labels.csv
    outs:
      - data/processed/features_for_training.csv
      - data/processed/labels_for_training.csv
      - data/processed/feature_scaler.pkl

  train:
    cmd: python src/train.py params.yaml
    deps:
      - src/train.py
      - src/model.py
      - data/processed/features_for_training.csv
      - data/processed/labels_for_training.csv
      - src/config.py
      - src/generate_labels.py
    params:
      - model
    outs:
      - models/trained_models/best_model.pt
      - models/trained_models/training_history.pkl

  predict:
    cmd: python src/predict.py
    deps:
      - src/predict.py
      - src/model.py
      - models/trained_models/best_model.pt
      - data/processed/processed_features.csv
    outs:
      - models/trained_models/new_predictions.csv

  evaluate:
    cmd: python src/evaluate.py params.yaml
    deps:
      - src/evaluate.py
      - models/trained_models/best_model.pt
      - data/processed/processed_features.csv
    outs:
      - models/trained_models/evaluation_metrics.pkl
      - models/trained_models/predictions.png
      - models/trained_models/residuals.png
      - models/trained_models/test_predictions.csv
